#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <span>
#include <string>

#include <d3d12.h>
#include <wrl/client.h>

#include "xenon/gpu/d3d12/command_queue.hpp"
#include "xenon/gpu/d3d12/memory.hpp"
#include "xenon/gpu/resource_ir.hpp"

namespace xenon::gpu::d3d12 {

// Native resource ABI shared with the HLSL generated by GPU 07. CPU-visible
// descriptors/constants are staged centrally, then snapshotted into the
// rotating submission frame before a draw is recorded. This prevents later
// guest state changes from mutating resources referenced by an in-flight draw.
class ResourceLayout {
 public:
  static constexpr std::uint32_t kTextureCount = 32;
  static constexpr std::uint32_t kSrvCount = 1 + kTextureCount * 4;
  static constexpr std::uint32_t kUavCount = 1;
  static constexpr std::uint32_t kMemoryExportDescriptor = kSrvCount;
  static constexpr std::uint32_t kResourceCount = kSrvCount + kUavCount;
  static constexpr std::uint32_t kSamplerCount = kTextureCount;
  static constexpr std::uint64_t kConstantBufferBytes = 9472;
  static constexpr std::uint32_t kFrameCount = CommandQueue::kFrameCount;

  [[nodiscard]] bool initialize(ID3D12Device* device);
  void reset() noexcept;
  [[nodiscard]] bool bind_guest_memory(ID3D12Resource* resource,
                                       std::uint64_t size);
  [[nodiscard]] bool bind_texture(std::uint32_t slot, TextureDimension dimension,
                                  ID3D12Resource* resource, DXGI_FORMAT format,
                                  std::uint32_t mip_levels,
                                  const TextureDescriptor& sampler_state);

  void prepare_draw(std::uint32_t frame_index, std::uint32_t draw_slot);
  [[nodiscard]] std::span<std::byte> constants() noexcept {
    return constants_staging_;
  }
  [[nodiscard]] bool ready() const noexcept { return root_signature_ != nullptr; }
  [[nodiscard]] ID3D12RootSignature* root_signature() const noexcept {
    return root_signature_.Get();
  }
  [[nodiscard]] ID3D12DescriptorHeap* resource_heap(
      std::uint32_t frame_index, std::uint32_t draw_slot) const noexcept {
    return frame_index < frames_.size() && draw_slot < CommandQueue::kBatchCommandCount
               ? frames_[frame_index].draws[draw_slot].resource_heap.Get()
               : nullptr;
  }
  [[nodiscard]] ID3D12DescriptorHeap* sampler_heap(
      std::uint32_t frame_index, std::uint32_t draw_slot) const noexcept {
    return frame_index < frames_.size() && draw_slot < CommandQueue::kBatchCommandCount
               ? frames_[frame_index].draws[draw_slot].sampler_heap.Get()
               : nullptr;
  }
  [[nodiscard]] ID3D12Resource* constants_resource(
      std::uint32_t frame_index, std::uint32_t draw_slot) const noexcept {
    return frame_index < frames_.size() && draw_slot < CommandQueue::kBatchCommandCount
               ? frames_[frame_index].draws[draw_slot].constants.resource()
               : nullptr;
  }
  [[nodiscard]] D3D12_GPU_DESCRIPTOR_HANDLE memory_export_handle(
      std::uint32_t frame_index, std::uint32_t draw_slot) const noexcept;
  [[nodiscard]] const std::string& error() const noexcept { return error_; }

 private:
  struct DrawBindings {
    Microsoft::WRL::ComPtr<ID3D12DescriptorHeap> resource_heap{};
    Microsoft::WRL::ComPtr<ID3D12DescriptorHeap> sampler_heap{};
    Buffer constants{};
    std::span<std::byte> constants_mapping{};
  };
  struct FrameBindings {
    std::array<DrawBindings, CommandQueue::kBatchCommandCount> draws{};
  };

  ID3D12Device* device_{};
  Microsoft::WRL::ComPtr<ID3D12RootSignature> root_signature_{};
  Microsoft::WRL::ComPtr<ID3D12DescriptorHeap> staging_resource_heap_{};
  Microsoft::WRL::ComPtr<ID3D12DescriptorHeap> staging_sampler_heap_{};
  std::array<FrameBindings, kFrameCount> frames_{};
  std::array<std::byte, kConstantBufferBytes> constants_staging_{};
  std::uint32_t resource_increment_{};
  std::uint32_t sampler_increment_{};
  std::string error_{};
};

}  // namespace xenon::gpu::d3d12
