#pragma once

#include <cstdint>
#include <string>

#include <d3d12.h>
#include <wrl/client.h>

#include "xenon/gpu/d3d12/memory.hpp"
#include "xenon/gpu/resource_ir.hpp"

namespace xenon::gpu::d3d12 {

// Native resource ABI shared with the HLSL generated by GPU 07. Texture
// arrays retain their Xenos fetch-constant indices; no game semantics or
// vertex locations are embedded in this layout.
class ResourceLayout {
 public:
  static constexpr std::uint32_t kTextureCount = 32;
  static constexpr std::uint32_t kSrvCount = 1 + kTextureCount * 4;
  static constexpr std::uint32_t kSamplerCount = kTextureCount;
  static constexpr std::uint64_t kConstantBufferBytes = 9472;

  [[nodiscard]] bool initialize(ID3D12Device* device);
  void reset() noexcept;
  [[nodiscard]] bool bind_guest_memory(ID3D12Resource* resource,
                                       std::uint64_t size);
  [[nodiscard]] bool bind_texture(std::uint32_t slot, TextureDimension dimension,
                                  ID3D12Resource* resource, DXGI_FORMAT format,
                                  std::uint32_t mip_levels,
                                  const TextureDescriptor& sampler_state);
  [[nodiscard]] bool ready() const noexcept { return root_signature_ != nullptr; }
  [[nodiscard]] ID3D12RootSignature* root_signature() const noexcept {
    return root_signature_.Get();
  }
  [[nodiscard]] ID3D12DescriptorHeap* resource_heap() const noexcept {
    return resource_heap_.Get();
  }
  [[nodiscard]] ID3D12DescriptorHeap* sampler_heap() const noexcept {
    return sampler_heap_.Get();
  }
  [[nodiscard]] Buffer& constants() noexcept { return constants_; }
  [[nodiscard]] const std::string& error() const noexcept { return error_; }

 private:
  ID3D12Device* device_{};
  Microsoft::WRL::ComPtr<ID3D12RootSignature> root_signature_{};
  Microsoft::WRL::ComPtr<ID3D12DescriptorHeap> resource_heap_{};
  Microsoft::WRL::ComPtr<ID3D12DescriptorHeap> sampler_heap_{};
  Buffer constants_{};
  std::uint32_t resource_increment_{};
  std::uint32_t sampler_increment_{};
  std::string error_{};
};

}  // namespace xenon::gpu::d3d12
