#!/usr/bin/env python3
"""Build the third-party source bundle that accompanies Xenon binary releases."""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import tempfile
import urllib.request
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OFFER_MANIFEST = ROOT / "tools" / "release" / "source_offer_manifest.json"
DEPS_MANIFEST = ROOT / "tools" / "deps" / "manifest.json"
SOURCE_OFFER = ROOT / "THIRD_PARTY_SOURCE_OFFER.md"


class SourceOfferError(RuntimeError):
    pass


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def download(url: str, expected: str, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.is_file() and sha256(destination) == expected:
        return
    destination.unlink(missing_ok=True)
    req = urllib.request.Request(url, headers={"User-Agent": "Xenon-Recomp release source offer"})
    try:
        with urllib.request.urlopen(req, timeout=180) as src, destination.open("wb") as out:
            shutil.copyfileobj(src, out, length=1024 * 1024)
    except Exception as exc:
        destination.unlink(missing_ok=True)
        raise SourceOfferError(f"failed downloading {url}: {exc}") from exc
    actual = sha256(destination)
    if actual != expected:
        destination.unlink(missing_ok=True)
        raise SourceOfferError(
            f"source archive hash mismatch for {url}: got {actual}, expected {expected}"
        )


def archive_ffmpeg(destination: Path, revision: str, repository: str) -> str:
    with tempfile.TemporaryDirectory(prefix="xenon-ffmpeg-source-") as td:
        repo = Path(td) / "ffmpeg"
        subprocess.run(["git", "init", str(repo)], check=True)
        subprocess.run(["git", "remote", "add", "origin", repository], cwd=repo, check=True)
        subprocess.run(["git", "fetch", "--depth", "1", "origin", revision], cwd=repo, check=True)
        subprocess.run(["git", "checkout", "--detach", "FETCH_HEAD"], cwd=repo, check=True)
        head = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=repo, text=True).strip()
        if head != revision:
            raise SourceOfferError(f"FFmpeg source revision mismatch: {head} != {revision}")
        prefix = f"xenia-ffmpeg-{revision[:12]}/"
        subprocess.run(
            ["git", "archive", "--format=tar.gz", f"--prefix={prefix}", "-o", str(destination), "HEAD"],
            cwd=repo,
            check=True,
        )
    return sha256(destination)


def build_bundle(output: Path, version: str, cache: Path) -> None:
    offer = json.loads(OFFER_MANIFEST.read_text(encoding="utf-8"))
    deps = json.loads(DEPS_MANIFEST.read_text(encoding="utf-8"))
    if offer.get("schema") != 1:
        raise SourceOfferError("unsupported source-offer manifest schema")

    cache.mkdir(parents=True, exist_ok=True)
    entries: list[dict[str, str]] = []
    source_files: list[Path] = []
    for item in offer["qt_sources"]:
        filename = Path(item["url"]).name
        path = cache / filename
        download(item["url"], item["sha256"], path)
        source_files.append(path)
        entries.append(
            {
                "component": item["name"],
                "version": offer["qt_version"],
                "file": filename,
                "sha256": item["sha256"],
                "upstream": item["url"],
            }
        )

    ffmpeg = deps["dependencies"]["xenia-ffmpeg"]
    ffmpeg_name = f"xenia-ffmpeg-{ffmpeg['revision'][:12]}-src.tar.gz"
    ffmpeg_path = cache / ffmpeg_name
    # Git archive gzip output is deterministic for a specific Git/tool version
    # but is generated by us, so record its actual hash in the release manifest.
    ffmpeg_hash = archive_ffmpeg(ffmpeg_path, ffmpeg["revision"], ffmpeg["repository"])
    source_files.append(ffmpeg_path)
    entries.append(
        {
            "component": "xenia-ffmpeg",
            "version": ffmpeg["version"],
            "revision": ffmpeg["revision"],
            "file": ffmpeg_name,
            "sha256": ffmpeg_hash,
            "upstream": ffmpeg["repository"],
        }
    )

    manifest = {
        "schema": 1,
        "xenon_release": version,
        "files": entries,
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
        zf.writestr("SOURCE_MANIFEST.json", json.dumps(manifest, indent=2, sort_keys=True) + "\n")
        zf.write(SOURCE_OFFER, SOURCE_OFFER.name)
        zf.write(ROOT / "THIRD_PARTY_NOTICES.md", "THIRD_PARTY_NOTICES.md")
        for source in source_files:
            zf.write(source, f"sources/{source.name}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", required=True)
    ap.add_argument("--output", type=Path, required=True)
    ap.add_argument("--cache", type=Path, default=ROOT / ".xenon" / "source-cache")
    args = ap.parse_args()
    build_bundle(args.output.resolve(), args.version, args.cache.resolve())
    print(f"Created {args.output.resolve()} ({sha256(args.output.resolve())})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
