if(XENON_BUILD_TESTS)

  if(TARGET xenon_audio)
    add_executable(xenon_audio_mixer_tests mixer_tests.cpp)
    target_link_libraries(xenon_audio_mixer_tests PRIVATE xenon_audio)
    xenon_enable_test_asserts(xenon_audio_mixer_tests)
    xenon_stage_runtime_dependencies(xenon_audio_mixer_tests)
    add_test(NAME xenon_audio_mixer_tests COMMAND xenon_audio_mixer_tests)
    add_executable(xenon_audio_xma_tests xma_tests.cpp)
    target_link_libraries(xenon_audio_xma_tests PRIVATE xenon_audio)
    xenon_enable_test_asserts(xenon_audio_xma_tests)
    xenon_stage_runtime_dependencies(xenon_audio_xma_tests)
    add_test(NAME xenon_audio_xma_tests COMMAND xenon_audio_xma_tests)
    add_executable(xenon_audio_system_tests system_tests.cpp)
    target_link_libraries(xenon_audio_system_tests PRIVATE xenon_audio)
    xenon_enable_test_asserts(xenon_audio_system_tests)
    xenon_stage_runtime_dependencies(xenon_audio_system_tests)
    add_test(NAME xenon_audio_system_tests COMMAND xenon_audio_system_tests)
    add_executable(xenon_audio_export_tests export_tests.cpp)
    target_link_libraries(xenon_audio_export_tests PRIVATE xenon_core)
    xenon_enable_test_asserts(xenon_audio_export_tests)
    xenon_stage_runtime_dependencies(xenon_audio_export_tests)
    add_test(NAME xenon_audio_export_tests COMMAND xenon_audio_export_tests)
  endif()
endif()
