#include <algorithm>
#include <fstream>
#include <iomanip>
#include <iterator>
#include <sstream>

#include "recomp/compilation/project_generation_internal.hpp"

namespace xenon::recomp::detail {

// Phase L (Part 2/16): deterministic shard assembly - a serial pass over
// already-computed text, in original order, identical regardless of how
// the parallel emission above was scheduled.
ShardLayout assemble_shards(const std::vector<const DiscoveredFunction*>& codegen_items,
                            const std::vector<std::string>& function_sources,
                            const DriverOptions& options) {
  std::vector<std::filesystem::path> shards;
  std::string shard_text;
  std::filesystem::path shard_path;
  // Part 4 (shard ownership): each codegen item's shard membership is
  // already a one-to-one function of its position in the deduplicated,
  // address-sorted `codegen_items`/`function_sources` (no function can
  // appear in two shards or twice in one - this loop visits `index` exactly
  // once each, strictly increasing). `shard_function_count_current`/`_max`
  // below are purely a diagnostic record of that fact (Part 9's
  // codegen_max_functions_per_shard), not an enforcement mechanism.
  std::size_t shard_function_count_current = 0;
  std::size_t shard_function_count_max = 0;
  std::size_t shard_bytes_current = 0;
  std::size_t shard_bytes_max = 0;
  constexpr std::size_t kHeaderSize = sizeof("// Generated by xenon codegen. Do not edit.\n") - 1;
  const auto flush_shard = [&] {
    if (shard_path.empty()) return;
    shard_function_count_max = std::max(shard_function_count_max, shard_function_count_current);
    shard_bytes_max = std::max(shard_bytes_max, shard_bytes_current);
    std::ifstream old(shard_path);
    const std::string previous((std::istreambuf_iterator<char>(old)), {});
    if (previous != shard_text) {
      std::ofstream output(shard_path);
      output << shard_text;
    }
  };
  const auto start_shard = [&](std::size_t index) {
    const auto path = options.output / "functions" / ("shard_" + [&] {
      std::ostringstream s;
      s << std::setfill('0') << std::setw(3)
        << (options.shard_max_bytes || options.shard_function_count == 1
                ? codegen_items[index]->guest_start
                : index / options.shard_function_count);
      return s.str();
    }() + ".cpp");
    shards.push_back(path);
    shard_path = path;
    shard_text = "// Generated by xenon codegen. Do not edit.\n";
    shard_function_count_current = 0;
    shard_bytes_current = kHeaderSize;
  };
  for (std::size_t index = 0; index < codegen_items.size(); ++index) {
    const auto& source = function_sources[index];
    if (options.shard_max_bytes) {
      // A shard always takes at least one function - a single function
      // larger than the budget gets its own oversized shard rather than an
      // empty one or a silently-unbounded one.
      const bool exceeds_budget =
          !shard_path.empty() && shard_bytes_current + source.size() > *options.shard_max_bytes;
      if (shard_path.empty() || exceeds_budget) {
        flush_shard();
        start_shard(index);
      }
    } else if (index % options.shard_function_count == 0) {
      flush_shard();
      start_shard(index);
    }
    shard_text += source;
    ++shard_function_count_current;
    shard_bytes_current += source.size();
  }
  flush_shard();
  return ShardLayout{std::move(shards), shard_function_count_max, shard_bytes_max};
}

// Function shards from an earlier generation that the current layout no
// longer names are removed so the generated build cannot pick them up.
void remove_stale_shards(const std::filesystem::path& function_directory,
                         const std::vector<std::filesystem::path>& shards) {
  std::error_code ec;
  for (const auto& entry : std::filesystem::directory_iterator(function_directory, ec)) {
    if (!entry.is_regular_file() || entry.path().extension() != ".cpp" ||
        entry.path().filename().string().find("shard_") != 0)
      continue;
    if (std::find(shards.begin(), shards.end(), entry.path()) == shards.end())
      std::filesystem::remove(entry.path(), ec);
  }
}

}  // namespace xenon::recomp::detail
