if(WIN32)
  set(XENON_HOST_PLATFORM "windows")
elseif(ANDROID)
  set(XENON_HOST_PLATFORM "android")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(XENON_HOST_PLATFORM "linux")
else()
  string(TOLOWER "${CMAKE_SYSTEM_NAME}" XENON_HOST_PLATFORM)
endif()
