if(XENON_BUILD_TESTS)

  add_executable(xenon_logger_stream_mutex_tests logger_stream_mutex_tests.cpp)
  target_link_libraries(xenon_logger_stream_mutex_tests PRIVATE xenon_logging)
  xenon_enable_test_asserts(xenon_logger_stream_mutex_tests)
  add_test(NAME xenon_logger_stream_mutex_tests COMMAND xenon_logger_stream_mutex_tests)
  add_executable(xenon_diagnostic_events_tests diagnostic_events_tests.cpp)
  target_link_libraries(xenon_diagnostic_events_tests PRIVATE xenon_logging)
  xenon_enable_test_asserts(xenon_diagnostic_events_tests)
  add_test(NAME xenon_diagnostic_events_tests COMMAND xenon_diagnostic_events_tests)
  add_executable(xenon_probe_log_tests probe_log_tests.cpp)
  target_link_libraries(xenon_probe_log_tests PRIVATE xenon_logging)
  xenon_enable_test_asserts(xenon_probe_log_tests)
  add_test(NAME xenon_probe_log_tests COMMAND xenon_probe_log_tests)
endif()
