#!/usr/bin/env python3
"""Generates src/xbox/unicode_case_tables.inc: the simple (single-character)
Unicode case mappings for the Basic Multilingual Plane that RtlUpcaseUnicodeChar
and RtlDowncaseUnicodeChar need.

The kernel's own tables (Nls844UnicodeCaseTable) are simple, per-character maps,
so a character whose case mapping expands to several characters (U+00DF -> "SS")
maps to itself. The tables are derived from the Unicode Character Database that
ships with the Python interpreter running this script; the generator records
that version in the output. Surrogates are excluded (a UTF-16 code unit in the
surrogate range is never case-mapped).

Usage: python tools/development/generate_unicode_case_tables.py > src/xbox/unicode_case_tables.inc
"""
import sys
import unicodedata


def simple_map(code_unit, method):
    ch = chr(code_unit)
    mapped = getattr(ch, method)()
    if len(mapped) != 1:
        return code_unit
    target = ord(mapped)
    return target if target <= 0xFFFF else code_unit


def table(method):
    pairs = []
    for cu in range(0x10000):
        if 0xD800 <= cu <= 0xDFFF:
            continue
        target = simple_map(cu, method)
        if target != cu:
            pairs.append((cu, target))
    return pairs


def emit(name, pairs):
    out = [f"constexpr CaseMapEntry {name}[] = {{"]
    line = "   "
    for cu, target in pairs:
        item = f" {{0x{cu:04X}, 0x{target:04X}}},"
        if len(line) + len(item) > 96:
            out.append(line)
            line = "   "
        line += item
    out.append(line)
    out.append("};")
    return "\n".join(out)


def main():
    up = table("upper")
    down = table("lower")
    print("// Generated by tools/development/generate_unicode_case_tables.py - do not edit.")
    print(f"// Unicode {unicodedata.unidata_version} simple case mappings (BMP, no surrogates).")
    print(f"// upcase: {len(up)} entries, downcase: {len(down)} entries.")
    print(emit("kUpcaseTable", up))
    print()
    print(emit("kDowncaseTable", down))


if __name__ == "__main__":
    sys.exit(main())
