if(XENON_BUILD_TESTS)

  if(XENON_ENABLE_KERNEL)
    if(XENON_ENABLE_MEMORY)
      add_executable(xenon_guest_heap_tests guest_heap_tests.cpp)
      target_link_libraries(xenon_guest_heap_tests PRIVATE xenon_kernel)
      xenon_enable_test_asserts(xenon_guest_heap_tests)
      add_test(NAME xenon_guest_heap_tests COMMAND xenon_guest_heap_tests)
    endif()
    add_executable(xenon_kernel_io_tests kernel_io_tests.cpp)
    target_link_libraries(xenon_kernel_io_tests PRIVATE xenon_kernel)
    xenon_enable_test_asserts(xenon_kernel_io_tests)
    add_test(NAME xenon_kernel_io_tests COMMAND xenon_kernel_io_tests)
    add_executable(xenon_kernel_synchronization_tests synchronization_tests.cpp)
    target_link_libraries(xenon_kernel_synchronization_tests PRIVATE xenon_kernel)
    xenon_enable_test_asserts(xenon_kernel_synchronization_tests)
    add_test(NAME xenon_kernel_synchronization_tests COMMAND xenon_kernel_synchronization_tests)
    add_executable(xenon_kernel_timer_dispatch_tests timer_dispatch_tests.cpp)
    target_link_libraries(xenon_kernel_timer_dispatch_tests PRIVATE xenon_kernel)
    xenon_enable_test_asserts(xenon_kernel_timer_dispatch_tests)
    add_test(NAME xenon_kernel_timer_dispatch_tests COMMAND xenon_kernel_timer_dispatch_tests)
    add_executable(xenon_kernel_exception_tests exception_tests.cpp)
    target_link_libraries(xenon_kernel_exception_tests PRIVATE xenon_kernel)
    xenon_enable_test_asserts(xenon_kernel_exception_tests)
    add_test(NAME xenon_kernel_exception_tests COMMAND xenon_kernel_exception_tests)
    add_executable(xenon_kernel_thread_lifecycle_tests thread_lifecycle_tests.cpp)
    target_link_libraries(xenon_kernel_thread_lifecycle_tests PRIVATE xenon_kernel)
    xenon_enable_test_asserts(xenon_kernel_thread_lifecycle_tests)
    add_test(NAME xenon_kernel_thread_lifecycle_tests COMMAND xenon_kernel_thread_lifecycle_tests)
  endif()

  if(TARGET xenon_xbox_kernel_io)
    add_executable(xenon_xbox_guest_io_tests xbox_guest_io_tests.cpp)
    target_link_libraries(xenon_xbox_guest_io_tests PRIVATE xenon_xbox_kernel_io)
    xenon_enable_test_asserts(xenon_xbox_guest_io_tests)
    add_test(NAME xenon_xbox_guest_io_tests COMMAND xenon_xbox_guest_io_tests)
  endif()
  if(TARGET xenon_kernel)
    xenon_add_standalone_test(xenon_kernel_infinite_wait_tests
      infinite_wait_tests.cpp xenon_kernel)
  endif()
endif()
